// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UESAN.SHOPPING.CORE.core.Entities;

public partial class Payment
{
    public int Id { get; set; }

    public int? OrdersId { get; set; }

    public decimal? TotalAmount { get; set; }

    public string PaymentMethod { get; set; }

    public string Status { get; set; }

    public virtual Order Orders { get; set; }
}